### ISSUE TITLE
Discuss how to handle dataframes in step outputs in memory mode and implement accordingly

### ISSUE THREAD

**Issue by lill28** [cschlaffner/PROTzilla2#62]
So far all dataframes in outputs of methods are saved on disk, even in memory mode. We should discuss whether in memory mode we should only save necessary dataframes on disk. Some of the output dataframes can be large as well. Saving them all on disk could defy the aim of memory mode.

outputs that can be inputs of other methods might have to be saved to disk to enable continuing the run.
  
## Acceptance Criteria
- [ ] decide which outputs should be saved on disk
- [ ] implement according to decision

**Comment by henninggaertner** [comment]
So.. memory mode has sort of changed meaning since now all the dataframes are saved to disk, always. In memory mode, the goal is to maintain a low memory profile, because of that the dataframes are deleted from memory by replacing them with a Path (str) to the location on disk. 
I guess what this is asking for is a mode where the dataframes are all kept in memory. I am closing this for now, as there is no apparent need and usually a background thread that saves data to disk is not the bottleneck, rather it is a lack of RAM, which is why a complete Memory-only mode does not seem very sensible.
